-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWV96T8x8XFYVnXTl
0aThWwqutfvYPdg+djsVBmCf4qygCgYIKoZIzj0DAQehRANCAAQyI1Mt1Jj+iEdV
ZD0T0lDpFshi0kYHJg54EC+6WbTkwW/LkXTRci0+PL41/DhYB1Vo0qf/VlmxnC/B
xMtAlmoK
-----END PRIVATE KEY-----