-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDL6psEpzYCCZZ50J
nTuzsnQk+L3aETWZb9pbIKq9BYCgCgYIKoZIzj0DAQehRANCAATI5YQfkoPxECOz
1lfyP/G4AwFJA3iGP+VWfAoxNHIh+9cfqS1eJYv1edrkv1O0COVS+nCLQ/uzp0x7
/Ao93aH5
-----END PRIVATE KEY-----